
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class Paneorderstore extends javax.swing.JPanel {

    DefaultListModel listModel1 = new DefaultListModel();
    DefaultListModel listModel2 = new DefaultListModel();

    /**
     * Creates new form Paneorderstore
     */
    public Paneorderstore() {
        initComponents();
        String data = "", str = "src/test.txt";
        try {
            data = new String(Files.readAllBytes(Paths.get(str)));
        } catch (IOException ex) {
            Logger.getLogger(Paneorderstore.class.getName()).log(Level.SEVERE, null, ex);
        }

        String[] totolly = data.split("/");
        for (int i = 0; i < totolly.length; i++) {
            String[] list = totolly[i].split("~");
            String fact = list[0] + "-" + list[1] + "-" + list[2] + "-" + list[3];
            System.out.println(fact);
            listModel1.addElement(fact);
        }
        jList1.setModel(listModel1);
//        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        jList1.setSelectedIndex(0);
//        jList1.addListSelectionListener(this);
//        jList1.setVisibleRowCount(5);
//        JScrollPane listScrollPane = new JScrollPane(jList1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(38, 50, 56));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(38, 50, 56));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "order list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(38, 50, 56));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(38, 50, 56));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Fulfil ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel3.add(jButton2, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel3.add(jButton1, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(38, 50, 56));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "stack", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jList3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(jList3);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
String str1="";
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        System.out.println(jList1.getSelectedValue());
        String[] str = jList1.getSelectedValue().toString().split("-");
        str1 = str1+jList1.getSelectedValue().toString()+"/";

        
        String fileName = "src/store.txt";
        byte[] buffer = str1.getBytes();
        FileOutputStream outputStream;
        try {
            outputStream = new FileOutputStream(fileName);
            outputStream.write(buffer);
            outputStream.close();
            System.out.println("Wrote " + buffer.length + " bytes");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Paneorderstore.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Paneorderstore.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        listModel2.addElement(jList1.getSelectedValue().toString());
        jList3.setModel(listModel2);
        int index = jList1.getSelectedIndex();
        listModel1.remove(index);
        jList1.setModel(listModel1);
//         jList1.invalidate();
//      jList1.validate();
        jList1.repaint();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] myArray = new String[50];
        for (int i = 0; i < jList3.getModel().getSize(); i++) {
            myArray[i] = String.valueOf(jList3.getModel().getElementAt(i));
        }
        String str="";
        for(int i=0; i<myArray.length; i++){
            str=myArray[i]+"/";
        }
//        String plus = "fgsdfg";
        String fileName = "src/store.txt";
        byte[] buffer = str.getBytes();
        FileOutputStream outputStream;
        try {
            outputStream = new FileOutputStream(fileName);
            outputStream.write(buffer);
            outputStream.close();
            System.out.println("Wrote " + buffer.length + " bytes");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Paneorderstore.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Paneorderstore.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
